name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          flags: unittests
          name: codecov
          fail_ci_if_error: true # optional (default = false)
